repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry:  python3 -m flake8 bitrs/ bitrs/test/ --indent-size=2 --statistics -j4 --max-line-length 150
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python3 -m mypy bitrs/bitrs.py bitrs/test/test_bitrs.py
        language: system
        always_run: true
        pass_filenames: false
      - id: tests
        name: tests
        entry: python3 -m pytest bitrs/test/
        language: system
        always_run: true
        pass_filenames: false
